ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
#
RUN addgroup -g ${PGID} -S alpine && \
    adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
RUN set -xe \
    && apk add --no-cache --purge -uU lua luarocks \
    && rm -rf /var/cache/apk/* /tmp/*
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/lua"]
